name: release version
on:
  workflow_dispatch:
    inputs: 
      CI_COMMIT_TAG:
        description: 'for release semantic versioning'
        required: true 
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: >
            [{
                "id": "rdc-releases",
                "username": "${{ secrets.MVN_USERNAME }}",
                "password": "${{ secrets.MVN_PASSWORD }}"
            }]
          profiles: >
            [{
                "id": "rdc",
                "properties": {"altReleaseDeploymentRepository": "rdc-releases::default::https://packages.aliyun.com/maven/repository/2040008-release-fvpoDf/"}
            }]
          active_profiles: >
            ["rdc"]
          output_file: /home/runner/.m2/settings.xml
      - name: Build Release
        run: |
          mvn -v
      - name: notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'cicd'
          slack-message: "github build result: ${{ job.status }} ,version ${{ inputs.CI_COMMIT_TAG }}  @here"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}